### ISSUE TITLE
WP Page not refreshing properly for new user to sign in

### ISSUE THREAD

**Issue by varunmahajan1** [surendhar153/one-tap-google-sign-in#13]
Homepage not refreshing to sign in automatically for a new user after clicking on the User account. 

When a user is clicking on the widget, a new account is made for the user but the user is not showing signed in.

The user needs to refresh the page manually to let them show they signed in.

**Comment by surendhar153** [comment]
can you share the url?

**Comment by Sylistron** [comment]
I have a solution for this as the problem is that the browser (depending on cache rules) may not understand that it needs to get a fresh copy of the redirect_url.  I added a "cache-busting" query string based on time() so class-gotl.php and that resolves the issue.  Working to get a fork() going and issuing a PR from there.

```
$current_url = home_url( add_query_arg( array(), $wp->request ) );
$current_url = add_query_arg( 'ts', time(), $current_url ); // new cache buster
```
